@URL = http://localhost:5009

GET {{URL}}/todos
Accept: application/json

###


GET {{URL}}/todos/complete
Accept: application/json

###

GET {{URL}}/todos/1
Accept: application/json

###



POST {{URL}}/todos
Accept: application/json
Content-Type: application/json

{
  "name": "My Task 3"
}

###


PUT {{URL}}/todos/1
Accept: application/json
Content-Type: application/json

{
  "name": "Edited task name",
  "isComplete": true
}

###


DELETE {{URL}}/todos/3
Accept: application/json

###